include:
  - path: pacha/compose.yaml
  - path: ddn/compose.yaml
services:
  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/certs:/certs
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config: